# PyTorch Tensors: The Foundation of Deep Learning

## What is a Tensor?

A **tensor** is a multi-dimensional array, similar to NumPy's ndarray, but with two key advantages:
1. **GPU acceleration** - Tensors can run on GPUs for faster computation
2. **Automatic differentiation** - PyTorch tracks operations for computing gradients

### Tensor Dimensions
- **0D tensor**: Scalar (single number)
- **1D tensor**: Vector (array)
- **2D tensor**: Matrix (table)
- **3D+ tensor**: Higher-dimensional arrays (e.g., images, videos)

> Reference: https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [1]:
# Import the essential libraries
import torch
import numpy as np

# Check PyTorch version and GPU availability
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.7.1+cu118
CUDA available: False


---

## Creating Tensors

There are multiple ways to create tensors in PyTorch. Let's explore the most common methods.

### From Python Data

In [2]:
# =============================================================================
# Creating a tensor directly from Python data (list, tuple, etc.)
# =============================================================================

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print("x_data:")
print(x_data)
print(f"\nShape: {x_data.shape}")        # torch.Size([2, 2])
print(f"Data type: {x_data.dtype}")      # torch.int64 (inferred from data)
print(f"Device: {x_data.device}")        # cpu (default)
print(f"Dimensions: {x_data.ndim}")      # 2 (it's a 2D tensor/matrix)

x_data:
tensor([[1, 2],
        [3, 4]])

Shape: torch.Size([2, 2])
Data type: torch.int64
Device: cpu
Dimensions: 2


### From NumPy Arrays

In [14]:
# =============================================================================
# Creating a tensor from NumPy array
# =============================================================================

data = [[1, 2], [3, 4]]

np_array = np.array(data)

print("NumPy array:")
print(np_array)
print(f"Shape: {np_array.shape}, dtype: {np_array.dtype}")

NumPy array:
[[1 2]
 [3 4]]
Shape: (2, 2), dtype: int64


In [15]:
# Convert NumPy array to PyTorch tensor
# Note: This shares memory with the original array by default!
x_np = torch.from_numpy(np_array)
print("\nTensor from NumPy:")
print(x_np)
print(f"Shape: {x_np.shape}, dtype: {x_np.dtype}")


Tensor from NumPy:
tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2]), dtype: torch.int64


In [18]:
# IMPORTANT: They share memory - modifying one affects the other!
np_array[0, 0] = 999
print(f"np_array[0,0] = \n {np_array}")
print(f"\nx_np[0,0] = \n {x_np}")  # Also changed!

np_array[0,0] = 
 [[999   2]
 [  3   4]]

x_np[0,0] = 
 tensor([[999,   2],
        [  3,   4]])


In [17]:
# Reset for later examples
np_array[0, 0] = 1

### From Another Tensor (Retaining Properties)

In [25]:
# =============================================================================
# Creating tensors that inherit shape/dtype from existing tensors
# =============================================================================

# The "_like" functions are useful for creating tensors with the same
# shape as another tensor (e.g., for initializing gradients, masks, etc.)

# zeros_like: Creates a tensor of zeros with the same shape and dtype
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Shape of original tensor: {x_data.shape}, dtype: {x_data.dtype}")
x_zeros = torch.zeros_like(x_data)
print("zeros_like(x_data):")
print(x_zeros)
print(f"Shape: {x_zeros.shape}, dtype: {x_zeros.dtype}")

Shape of original tensor: torch.Size([2, 2]), dtype: torch.int64
zeros_like(x_data):
tensor([[0, 0],
        [0, 0]])
Shape: torch.Size([2, 2]), dtype: torch.int64


In [27]:
# ones_like: Creates a tensor of ones
x_ones = torch.ones_like(x_data)
print("\nones_like(x_data):")
print(x_ones)
print(f"Shape: {x_ones.shape}, dtype: {x_ones.dtype}")


ones_like(x_data):
tensor([[1, 1],
        [1, 1]])
Shape: torch.Size([2, 2]), dtype: torch.int64


In [28]:
# rand_like: Creates a tensor with random values [0, 1)
# You can override the dtype if needed
x_rand = torch.rand_like(x_data, dtype=torch.float32)
print("\nrand_like(x_data, dtype=float32):")
print(x_rand)
print(f"dtype: {x_rand.dtype}")  # Now float32 instead of int64


rand_like(x_data, dtype=float32):
tensor([[0.3322, 0.8717],
        [0.5361, 0.3260]])
dtype: torch.float32


### With Random or Constant Values

In [ ]:
# =============================================================================
# Creating tensors with specific values
# =============================================================================

shape = (2, 3)

# Random values from uniform distribution [0, 1) using rand
rand_tensor = torch.rand(shape)
print(f"torch.rand{shape}:")
print(rand_tensor)

torch.rand(2, 3):
tensor([[0.6476, 0.8598, 0.9326],
        [0.1951, 0.6621, 0.6096]])


In [ ]:
# Random values from standard normal distribution (mean=0, std=1) using randn
randn_tensor = torch.randn(shape)
print(f"\ntorch.randn{shape} (normal distribution):")
print(randn_tensor)


torch.randn(2, 3) (normal distribution):
tensor([[-0.3812, -0.3822,  1.3878],
        [-0.7554, -1.2169, -0.0414]])


In [ ]:
# All ones
ones_tensor = torch.ones(shape)
print(f"\ntorch.ones{shape}:")
print(ones_tensor)


torch.ones (2, 3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [36]:
# All zeros
zeros_tensor = torch.zeros(shape)
print(f"\ntorch.zeros{shape}:")
print(zeros_tensor)


torch.zeros(2, 3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
# All same value
full_tensor = torch.full(shape, fill_value=7)
print(f"\ntorch.full{shape}, fill_value=7):")
print(full_tensor)


torch.full(2, 3), fill_value=7):
tensor([[7, 7, 7],
        [7, 7, 7]])


### More Creation Functions

In [38]:
# =============================================================================
# Additional useful tensor creation functions
# =============================================================================

# arange: Like Python's range(), creates evenly spaced values
arange_tensor = torch.arange(start=0, end=10, step=2)
print("torch.arange(0, 10, 2):")
print(arange_tensor)

torch.arange(0, 10, 2):
tensor([0, 2, 4, 6, 8])


In [39]:
# linspace: Creates n evenly spaced values between start and end (inclusive)
linspace_tensor = torch.linspace(start=0, end=1, steps=5)
print("\ntorch.linspace(0, 1, steps=5):")
print(linspace_tensor)


torch.linspace(0, 1, steps=5):
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [40]:
# eye: Identity matrix (1s on diagonal, 0s elsewhere)
eye_tensor = torch.eye(3)
print("\ntorch.eye(3):")
print(eye_tensor)


torch.eye(3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [41]:
# empty: Uninitialized tensor (faster, but contains garbage values)
# Use when you'll immediately overwrite all values
empty_tensor = torch.empty(2, 3)
print("\ntorch.empty(2, 3) - contains uninitialized values:")
print(empty_tensor)


torch.empty(2, 3) - contains uninitialized values:
tensor([[3.1410e-12, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [42]:
# randint: Random integers in range [low, high)
randint_tensor = torch.randint(low=0, high=10, size=(2, 3))
print("\ntorch.randint(0, 10, size=(2, 3)):")
print(randint_tensor)


torch.randint(0, 10, size=(2, 3)):
tensor([[5, 3, 4],
        [6, 6, 1]])


---

## Tensor Data Types (dtypes)

PyTorch tensors have specific data types that affect precision, memory usage, and GPU compatibility.

### Common Data Types
| dtype | Description | Use Case |
|-------|-------------|----------|
| `torch.float32` | 32-bit float (default) | Most neural network operations |
| `torch.float64` | 64-bit float | High precision calculations |
| `torch.float16` | 16-bit float | GPU memory optimization |
| `torch.int64` | 64-bit integer | Indices, labels |
| `torch.int32` | 32-bit integer | Smaller indices |
| `torch.bool` | Boolean | Masks, conditions |

In [43]:
# =============================================================================
# Specifying and converting data types
# =============================================================================

# Specify dtype at creation time
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)

print(f"float_tensor: {float_tensor}, dtype: {float_tensor.dtype}")
print(f"int_tensor: {int_tensor}, dtype: {int_tensor.dtype}")
print(f"bool_tensor: {bool_tensor}, dtype: {bool_tensor.dtype}")

float_tensor: tensor([1., 2., 3.]), dtype: torch.float32
int_tensor: tensor([1, 2, 3]), dtype: torch.int64
bool_tensor: tensor([ True, False,  True]), dtype: torch.bool


In [45]:
# Convert between dtypes using .to() method
x = torch.tensor([1, 2, 3])
print(f"\nOriginal: {x}, dtype: {x.dtype}")

x_float = x.to(torch.float32)
print(f"to(float32): {x_float}, dtype: {x_float.dtype}")

x_double = x.to(torch.float64)
print(f"to(float64): {x_double}, dtype: {x_double.dtype}")


Original: tensor([1, 2, 3]), dtype: torch.int64
to(float32): tensor([1., 2., 3.]), dtype: torch.float32
to(float64): tensor([1., 2., 3.], dtype=torch.float64), dtype: torch.float64


In [46]:
# Shortcut methods for common conversions
print("\nShortcut methods:")
print(f".float(): {x.float()}, dtype: {x.float().dtype}")
print(f".long(): {x.long()}, dtype: {x.long().dtype}")
print(f".double(): {x.double()}, dtype: {x.double().dtype}")
print(f".bool(): {x.bool()}, dtype: {x.bool().dtype}")


Shortcut methods:
.float(): tensor([1., 2., 3.]), dtype: torch.float32
.long(): tensor([1, 2, 3]), dtype: torch.int64
.double(): tensor([1., 2., 3.], dtype=torch.float64), dtype: torch.float64
.bool(): tensor([True, True, True]), dtype: torch.bool


---

## Tensor Attributes

Every tensor has important attributes that describe its properties.

In [47]:
# =============================================================================
# Key tensor attributes
# =============================================================================

tensor = torch.randn(3, 4, 5)

print("Tensor Attributes:")
print("-" * 40)
print(f"Shape:        {tensor.shape}")        # Size of each dimension
print(f"Size:         {tensor.size()}")       # Same as shape (method)
print(f"Dimensions:   {tensor.ndim}")         # Number of dimensions
print(f"Num elements: {tensor.numel()}")      # Total number of elements
print(f"Data type:    {tensor.dtype}")        # Data type
print(f"Device:       {tensor.device}")       # cpu or cuda
print(f"Contiguous:   {tensor.is_contiguous()}")  # Memory layout

Tensor Attributes:
----------------------------------------
Shape:        torch.Size([3, 4, 5])
Size:         torch.Size([3, 4, 5])
Dimensions:   3
Num elements: 60
Data type:    torch.float32
Device:       cpu
Contiguous:   True


In [48]:
# Individual dimension sizes
print(f"\nDimension sizes:")
for i in range(tensor.ndim):
    print(f"  Dim {i}: {tensor.size(i)}")


Dimension sizes:
  Dim 0: 3
  Dim 1: 4
  Dim 2: 5


---

## Tensor Operations

PyTorch provides a comprehensive set of operations for tensors. Full list: https://docs.pytorch.org/docs/stable/torch.html

### Moving Tensors to GPU

In [49]:
# =============================================================================
# Moving tensors between devices (CPU <-> GPU)
# =============================================================================

tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f"Original device: {tensor.device}")

# Check if CUDA (GPU) is available
if torch.cuda.is_available():
    # Move to GPU
    tensor_gpu = tensor.to('cuda')
    print(f"After .to('cuda'): {tensor_gpu.device}")
    
    # Alternative: specify GPU index
    # tensor_gpu = tensor.to('cuda:0')
    
    # Move back to CPU
    tensor_cpu = tensor_gpu.to('cpu')
    print(f"After .to('cpu'): {tensor_cpu.device}")
    
    # Shortcut methods
    # tensor.cuda()  # Move to default GPU
    # tensor.cpu()   # Move to CPU
else:
    print("CUDA not available - tensors stay on CPU")
    print("Tip: GPU operations are much faster for large tensors!")

# IMPORTANT: Operations between tensors must be on the same device
# tensor_cpu + tensor_gpu  # This would raise an error!

Original device: cpu
CUDA not available - tensors stay on CPU
Tip: GPU operations are much faster for large tensors!


### Indexing and Slicing

Tensor indexing works like NumPy arrays.

In [50]:
# =============================================================================
# Indexing and slicing tensors
# =============================================================================

x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("Original tensor x (3x4):")
print(x)

Original tensor x (3x4):
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [51]:
# Basic indexing
print(f"\nx[0] (first row): {x[0]}")
print(f"x[0, 0] (first element): {x[0, 0]}")
print(f"x[-1] (last row): {x[-1]}")


x[0] (first row): tensor([1, 2, 3, 4])
x[0, 0] (first element): 1
x[-1] (last row): tensor([ 9, 10, 11, 12])


In [52]:
# Slicing: [start:end:step] - end is exclusive
print(f"\nx[:, 0] (first column): {x[:, 0]}")
print(f"x[0:2, 1:3] (rows 0-1, cols 1-2):\n{x[0:2, 1:3]}")
print(f"x[::2] (every other row):\n{x[::2]}")


x[:, 0] (first column): tensor([1, 5, 9])
x[0:2, 1:3] (rows 0-1, cols 1-2):
tensor([[2, 3],
        [6, 7]])
x[::2] (every other row):
tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])


In [53]:
# Using ... (ellipsis) for remaining dimensions
print(f"\nx[..., -1] (last column): {x[..., -1]}")


x[..., -1] (last column): tensor([ 4,  8, 12])


In [54]:
# =============================================================================
# Modifying tensors using indexing
# =============================================================================

x = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("Original tensor x:")
print(x)

Original tensor x:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [55]:
# Set entire column to a single value
x[:, 1] = 0
print("After x[:, 1] = 0:")
print(x)

After x[:, 1] = 0:
tensor([[ 1,  0,  3,  4],
        [ 5,  0,  7,  8],
        [ 9,  0, 11, 12]])


In [56]:
# Set values using boolean mask
x[x > 8] = 99
print("\nAfter x[x > 8] = 99:")
print(x)


After x[x > 8] = 99:
tensor([[ 1,  0,  3,  4],
        [ 5,  0,  7,  8],
        [99,  0, 99, 99]])


### Joining Tensors

`cat()` concatenates along an existing dimension

In [57]:
# =============================================================================
# torch.cat - Concatenate along existing dimension
# =============================================================================

x = torch.tensor([[1, 2], [3, 4]])
print(f"x (shape {x.shape}):\n{x}\n")

x (shape torch.Size([2, 2])):
tensor([[1, 2],
        [3, 4]])



In [58]:
# dim=0: Concatenate along rows (stack vertically)
t1 = torch.cat([x, x, x], dim=0)
print(f"cat([x, x, x], dim=0) - shape {t1.shape}:")
print(t1)

cat([x, x, x], dim=0) - shape torch.Size([6, 2]):
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


In [59]:
# dim=1: Concatenate along columns (stack horizontally)
t2 = torch.cat([x, x], dim=1)
print(f"\ncat([x, x], dim=1) - shape {t2.shape}:")
print(t2)


cat([x, x], dim=1) - shape torch.Size([2, 4]):
tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])


 `stack()` creates a new dimension.

In [60]:
# =============================================================================
# torch.stack - Stack tensors along a NEW dimension
# =============================================================================

# stack() adds a new dimension, unlike cat() which extends an existing one

x = torch.tensor([[1, 2], [3, 4]])  # Shape: (2, 2)
print(f"x (shape {x.shape}):\n{x}\n")

x (shape torch.Size([2, 2])):
tensor([[1, 2],
        [3, 4]])



In [67]:
# dim=0: New dimension at position 0
# Shape: (2, 2) -> (2, 2, 2)
t3 = torch.stack([x, x], dim=0)
print(f"stack([x, x], dim=0) - shape {t3.shape}")
print(f"It becomes: 2 matrices of shape (2, 2)\n")
print("t3:")
print(t3)

stack([x, x], dim=0) - shape torch.Size([2, 2, 2])
It becomes: 2 matrices of shape (2, 2)

t3:
tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])


In [69]:
# dim=1: New dimension at position 1
# Shape: (2, 2) -> (2, 2, 2) but organized differently
t4 = torch.stack([x, x], dim=1)
print(f"stack([x, x], dim=1) - shape {t4.shape}")
print("\nt4:")
print(t4)

stack([x, x], dim=1) - shape torch.Size([2, 2, 2])

t4:
tensor([[[1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4]]])


In [70]:
# dim=2: New dimension at position 2
t5 = torch.stack([x, x], dim=2)
print(f"stack([x, x], dim=2) - shape {t5.shape}")
print("\nt5:")
print(t5)

# Key difference from cat:
# cat([x, x], dim=0).shape = (4, 2)  - extends existing dim
# stack([x, x], dim=0).shape = (2, 2, 2)  - creates new dim

stack([x, x], dim=2) - shape torch.Size([2, 2, 2])

t5:
tensor([[[1, 1],
         [2, 2]],

        [[3, 3],
         [4, 4]]])


### Reshaping Tensors

Reshaping allows you to change the dimensions of a tensor without changing its data.

In [71]:
# =============================================================================
# Reshaping operations
# =============================================================================

x = torch.arange(12)  # [0, 1, 2, ..., 11]
print(f"Original x (shape {x.shape}): {x}\n")

Original x (shape torch.Size([12])): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])



In [78]:
# view: Reshape tensor (must be contiguous in memory)
# contiguouys means that the data is stored in a single, unbroken block of memory
v = x.view(3, 4)
print(f"x.view(3, 4) - shape {v.shape}:")
print(v)

x.view(3, 4) - shape torch.Size([3, 4]):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [79]:
# reshape: Like view, but works on non-contiguous tensors (may copy data)
r = x.reshape(2, 6)
print(f"\nx.reshape(2, 6) - shape {r.shape}:")
print(r)


x.reshape(2, 6) - shape torch.Size([2, 6]):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [82]:
# Use -1 to infer dimension automatically
auto = x.view(4, -1)  # -1 becomes 3 (12/4=3)
print(f"\nx.view(4, -1) - shape {auto.shape}")
print(auto)


x.view(4, -1) - shape torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [84]:
# flatten: Collapse all dimensions into 1D
print("\nOriginal v:"
      f"\n{v}")
f = v.flatten()
print(f"\nv.flatten() - shape {f.shape}: {f}")


Original v:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

v.flatten() - shape torch.Size([12]): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [101]:
# squeeze: Remove dimensions of size 1
y = torch.zeros(2, 1, 3, 1)
print(f"\nOriginal y (shape {y.shape}):")
print(y)
squeezed = y.squeeze()
print(f"\nAfter squeeze(): {squeezed.shape}")
print(squeezed)
print("\nOnly remove last dim using squeeze(-1):")
print(y.squeeze(-1).shape)
print(y.squeeze(-1))


Original y (shape torch.Size([2, 1, 3, 1])):
tensor([[[[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]]]])

After squeeze(): torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Only remove last dim using squeeze(-1):
torch.Size([2, 1, 3])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])


In [96]:
# unsqueeze: Add a dimension of size 1
z = torch.tensor([1, 2, 3])
print(f"\nOriginal z shape: {z.shape}")
print(f"z: {z}")
print(f"\nz.unsqueeze(0) shape: {z.unsqueeze(0).shape}")  # Add batch dim
print("z.unsqueeze(0): \n", z.unsqueeze(0), "\n")
print(f"z.unsqueeze(1) shape: {z.unsqueeze(1).shape}")  # Add column dim
print("z.unsqueeze(1): \n", z.unsqueeze(1))


Original z shape: torch.Size([3])
z: tensor([1, 2, 3])

z.unsqueeze(0) shape: torch.Size([1, 3])
z.unsqueeze(0): 
 tensor([[1, 2, 3]]) 

z.unsqueeze(1) shape: torch.Size([3, 1])
z.unsqueeze(1): 
 tensor([[1],
        [2],
        [3]])


In [102]:
# =============================================================================
# Transpose and permute
# =============================================================================

x = torch.randn(2, 3, 4)
print(f"Original shape: {x.shape}")

Original shape: torch.Size([2, 3, 4])


In [103]:
# transpose: Swap two specific dimensions
t = x.transpose(0, 2)  # Swap dims 0 and 2
print(f"transpose(0, 2): {t.shape}")

transpose(0, 2): torch.Size([4, 3, 2])


In [104]:
# permute: Reorder all dimensions at once
p = x.permute(2, 0, 1)  # New order: dim2, dim0, dim1
print(f"permute(2, 0, 1): {p.shape}")

permute(2, 0, 1): torch.Size([4, 2, 3])


In [105]:
# For 2D tensors, .T is a shortcut for transpose
m = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nMatrix shape: {m.shape}")
print(f"Matrix.T shape: {m.T.shape}")


Matrix shape: torch.Size([2, 3])
Matrix.T shape: torch.Size([3, 2])


### Reduction Operations

These operations reduce tensor dimensions by aggregating values.

In [116]:
# =============================================================================
# Reduction operations: sum, mean, max, min, etc.
# =============================================================================

x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(f"x (shape {x.shape}):\n{x}\n")

x (shape torch.Size([2, 3])):
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [117]:
# Reduce entire tensor to single value
print(f"sum:  {x.sum()}")
print(f"mean: {x.mean()}")
print(f"max:  {x.max()}")
print(f"min:  {x.min()}")
print(f"std:  {x.std():.4f}")

sum:  21.0
mean: 3.5
max:  6.0
min:  1.0
std:  1.8708


In [118]:
# Reduce along specific dimension
print(f"\nsum(dim=0) - sum each column: {x.sum(dim=0)}")
print(f"sum(dim=1) - sum each row:    {x.sum(dim=1)}")
print(f"mean(dim=1) - mean each row:  {x.mean(dim=1)}")


sum(dim=0) - sum each column: tensor([5., 7., 9.])
sum(dim=1) - sum each row:    tensor([ 6., 15.])
mean(dim=1) - mean each row:  tensor([2., 5.])


In [ ]:
print(f"Original x (shape {x.shape}):\n{x}\n")

# max/min return both values and indices
values, indices = x.max(dim=1)
print(f"\nmax(dim=1):")
print(f"  values:  {values}")
print(f"  indices: {indices}")

Original x (shape torch.Size([2, 3])):
tensor([[1., 2., 3.],
        [4., 5., 6.]])


max(dim=1):
  values:  tensor([3., 6.])
  indices: tensor([2, 2])


In [ ]:
print(f"Original x (shape {x.shape}):\n{x}\n")

# argmax/argmin return only indices
print(f"\nargmax (flattened): {x.argmax()}")  # 5 - Max value 6 is at index 5

print(f"argmax(dim=0):      {x.argmax(dim=0)}")  # Index along dim 0 - tensor([1, 1, 1])
# argmax(dim=0) = [1, 1, 1]
# - Compares rows for each column:
# - Col 0: 4 > 1 → row 1
# - Col 1: 5 > 2 → row 1
# - Col 2: 6 > 3 → row 1

print(f"argmax(dim=1):      {x.argmax(dim=1)}")  # Index along dim 1 - tensor([2, 2])
# argmax(dim=1) = [2, 2]
# - Compares columns for each row:
# - Row 0: max is 3 → col 2
# - Row 1: max is 6 → col 2

Original x (shape torch.Size([2, 3])):
tensor([[1., 2., 3.],
        [4., 5., 6.]])


argmax (flattened): 5
argmax(dim=0):      tensor([1, 1, 1])
argmax(dim=1):      tensor([2, 2])


### Arithmetic Operations

In [121]:
# =============================================================================
# Element-wise operations
# =============================================================================

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("a:\n", a)
print("b:\n", b)

a:
 tensor([[1, 2],
        [3, 4]])
b:
 tensor([[5, 6],
        [7, 8]])


In [122]:
# Element-wise operations: +, -, *, /, **
print("\nElement-wise operations:")
print(f"a + b:\n{a + b}")
print(f"a * b:\n{a * b}")
print(f"a ** 2:\n{a ** 2}")


Element-wise operations:
a + b:
tensor([[ 6,  8],
        [10, 12]])
a * b:
tensor([[ 5, 12],
        [21, 32]])
a ** 2:
tensor([[ 1,  4],
        [ 9, 16]])


In [123]:
# Same using torch functions
print("\nUsing torch functions:")
print(f"torch.add(a, b):\n{torch.add(a, b)}")
print(f"torch.mul(a, b):\n{torch.mul(a, b)}")
print(f"torch.pow(a, 2):\n{torch.pow(a, 2)}")


Using torch functions:
torch.add(a, b):
tensor([[ 6,  8],
        [10, 12]])
torch.mul(a, b):
tensor([[ 5, 12],
        [21, 32]])
torch.pow(a, 2):
tensor([[ 1,  4],
        [ 9, 16]])


In [124]:
# =============================================================================
# Matrix multiplication
# =============================================================================

# Note: Element-wise multiplication (*) is different from matrix multiplication!

x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
y = torch.tensor([[1, 2], [3, 4], [5, 6]])  # Shape: (3, 2)

print(f"x (shape {x.shape}):\n{x}")
print(f"\ny (shape {y.shape}):\n{y}")


x (shape torch.Size([2, 3])):
tensor([[1, 2, 3],
        [4, 5, 6]])

y (shape torch.Size([3, 2])):
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [125]:
# Matrix multiplication: (2x3) @ (3x2) = (2x2)
result = torch.matmul(x, y)
print(f"\ntorch.matmul(x, y) - shape {result.shape}:")
print(result)


torch.matmul(x, y) - shape torch.Size([2, 2]):
tensor([[22, 28],
        [49, 64]])


In [126]:
# Alternative syntaxes
print(f"\nx @ y:\n{x @ y}")  # @ operator
print(f"\ntorch.mm(x, y):\n{torch.mm(x, y)}")  # Only for 2D


x @ y:
tensor([[22, 28],
        [49, 64]])

torch.mm(x, y):
tensor([[22, 28],
        [49, 64]])


In [127]:
# Transpose for when dimensions don't match
z = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
print(f"\nz @ z.T (shape {(z @ z.T).shape}):\n{z @ z.T}")


z @ z.T (shape torch.Size([2, 2])):
tensor([[14, 32],
        [32, 77]])


### NumPy Interoperability

In [128]:
# =============================================================================
# Tensor to NumPy
# =============================================================================

tensor = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(f"Tensor:\n{tensor}")
print(f"Shape: {tensor.shape}, dtype: {tensor.dtype}")

Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3]), dtype: torch.float32


In [129]:
# Convert to NumPy - shares memory by default (on CPU)
numpy_array = tensor.numpy()
print(f"\nNumPy array:\n{numpy_array}")
print(f"Shape: {numpy_array.shape}, dtype: {numpy_array.dtype}")


NumPy array:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3), dtype: float32


In [130]:
# They share memory - modifying one affects the other
tensor[0, 0] = 999
print(f"\nAfter tensor[0,0] = 999:")
print(f"tensor[0,0] = {tensor[0,0]}")
print(f"numpy_array[0,0] = {numpy_array[0,0]}")  # Also changed!

# To get a separate copy:
# numpy_copy = tensor.clone().numpy()


After tensor[0,0] = 999:
tensor[0,0] = 999.0
numpy_array[0,0] = 999.0


In [131]:
# or change numpy array to tensor
numpy_array = np.random.rand(3,4)
print("\nnumpy_array: \n", numpy_array)
print("Shape of numpy_array: ", numpy_array.shape)
print("Datatype of numpy_array: ", numpy_array.dtype)


numpy_array: 
 [[0.73366788 0.9859529  0.88846274 0.61296789]
 [0.16225389 0.82216389 0.24644636 0.98026713]
 [0.89742194 0.35655514 0.51471602 0.73312017]]
Shape of numpy_array:  (3, 4)
Datatype of numpy_array:  float64


In [133]:
tensor_from_numpy = torch.from_numpy(numpy_array)
print("\ntensor_from_numpy: \n", tensor_from_numpy)
print("Shape of tensor_from_numpy: ", tensor_from_numpy.shape)
print("Datatype of tensor_from_numpy: ", tensor_from_numpy.dtype)


tensor_from_numpy: 
 tensor([[0.7337, 0.9860, 0.8885, 0.6130],
        [0.1623, 0.8222, 0.2464, 0.9803],
        [0.8974, 0.3566, 0.5147, 0.7331]], dtype=torch.float64)
Shape of tensor_from_numpy:  torch.Size([3, 4])
Datatype of tensor_from_numpy:  torch.float64


### In-Place Operations

Operations ending with `_` modify tensors in place (saves memory but be careful!).

In [134]:
# =============================================================================
# In-place operations (modify tensor directly)
# =============================================================================

x = torch.tensor([1., 2., 3.])
print(f"Original: {x}")
print(f"Memory address: {hex(id(x))}")

Original: tensor([1., 2., 3.])
Memory address: 0x76206a5a9a90


In [135]:
# In-place operations have an underscore suffix
x.add_(5)  # Same as x = x + 5, but modifies x directly
print(f"\nAfter x.add_(5): {x}")
print(f"Memory address: {hex(id(x))}")  # Same address!

# Common in-place operations:
# add_(), sub_(), mul_(), div_()
# zero_(), fill_(), copy_()
# clamp_(), abs_(), sqrt_()


After x.add_(5): tensor([6., 7., 8.])
Memory address: 0x76206a5a9a90


In [136]:
# Example: clamp values to a range
y = torch.tensor([-2., 0., 3., 5.])
y.clamp_(min=0, max=4)
print(f"\nAfter clamp_(0, 4): {y}")

# WARNING: In-place operations can break gradient computation
# because they destroy the original values needed for backprop.
# Avoid them in training code when requires_grad=True.


After clamp_(0, 4): tensor([0., 0., 3., 4.])


### Cloning and Memory Sharing

Understanding when tensors share memory is crucial for avoiding bugs.

In [137]:
# =============================================================================
# Clone vs View: Memory sharing
# =============================================================================

original = torch.tensor([1., 2., 3.])
print(f"Original tensor: {original}")

Original tensor: tensor([1., 2., 3.])


In [138]:
# view() shares memory with original
viewed = original.view(3, 1)
print("view() shares memory:")
original[0] = 999
print(f"  original: {original}")
print(f"  viewed:   {viewed.flatten()}")  # Also changed!

view() shares memory:
  original: tensor([999.,   2.,   3.])
  viewed:   tensor([999.,   2.,   3.])


In [139]:
# Reset
original[0] = 1

In [140]:
# clone() creates an independent copy
cloned = original.clone()
print("\nclone() creates independent copy:")
original[0] = 888
print(f"  original: {original}")
print(f"  cloned:   {cloned}")  # Unchanged!

# detach() vs clone():
# - clone(): Creates a copy with same requires_grad
# - detach(): Returns a view that doesn't require grad
# - detach().clone(): Independent copy without gradient tracking


clone() creates independent copy:
  original: tensor([888.,   2.,   3.])
  cloned:   tensor([1., 2., 3.])


### Comparison Operations

In [141]:
# =============================================================================
# Comparison and logical operations
# =============================================================================

x = torch.tensor([1, 2, 3, 4, 5])
print("Original tensor: ")
print(x)

Original tensor: 
tensor([1, 2, 3, 4, 5])


In [142]:
# Comparison returns boolean tensors
print(f"x: {x}")
print(f"x > 3:  {x > 3}")
print(f"x == 3: {x == 3}")
print(f"x != 3: {x != 3}")

x: tensor([1, 2, 3, 4, 5])
x > 3:  tensor([False, False, False,  True,  True])
x == 3: tensor([False, False,  True, False, False])
x != 3: tensor([ True,  True, False,  True,  True])


In [143]:
# Using torch functions
print(f"\ntorch.gt(x, 3): {torch.gt(x, 3)}")  # greater than
print(f"torch.eq(x, 3): {torch.eq(x, 3)}")  # equal


torch.gt(x, 3): tensor([False, False, False,  True,  True])
torch.eq(x, 3): tensor([False, False,  True, False, False])


In [144]:
# Boolean indexing - select elements that match condition
print(f"\nx[x > 3]: {x[x > 3]}")


x[x > 3]: tensor([4, 5])


In [145]:
# Any and all
print(f"\n(x > 3).any(): {(x > 3).any()}")  # At least one True
print(f"(x > 3).all(): {(x > 3).all()}")  # All True
print(f"(x > 0).all(): {(x > 0).all()}")  # All True


(x > 3).any(): True
(x > 3).all(): False
(x > 0).all(): True


In [ ]:
# Useful for conditional logic
mask = x > 2
result = torch.where(condition=mask, input=x * 10, other=x)  # If mask: x*10, else: x
print(f"\nwhere(x > 2, x*10, x): {result}")


where(x > 2, x*10, x): tensor([ 1,  2, 30, 40, 50])


---

## Deep Dive: Matrix Multiplication Functions

PyTorch has several functions for matrix multiplication. Here's when to use each one.

### torch.mul

In [20]:
# 1. torch.mul - Element-wise multiplication (works on any shape, no matrix multiplication)
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print("a:\n", a, "\n")
print("b:\n", b, "\n")
print("torch.mul(a, b):\n", torch.mul(a, b), "\n")
print("Same as a * b:\n", a * b)

a:
 tensor([[1, 2],
        [3, 4]]) 

b:
 tensor([[5, 6],
        [7, 8]]) 

torch.mul(a, b):
 tensor([[ 5, 12],
        [21, 32]]) 

Same as a * b:
 tensor([[ 5, 12],
        [21, 32]])


### torch.mm

In [3]:
# torch.mm - Strict 2D matrix multiplication (only works with 2D tensors)

x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2x3
print("x (2x3):\n", x, "\n")
print(f"shape of x: {x.shape}, dimensions: {x.dim()}")
print(f"x is a {x.dim()}D tensor\n")

y = torch.tensor([[7, 8], [9, 10], [11, 12]])  # 3x2
print("y (3x2):\n", y, "\n")
print(f"shape of y: {y.shape}, dimensions: {y.dim()}")
print(f"y is a {y.dim()}D tensor\n")
print("torch.mm(x, y) (2x2):\n", torch.mm(x, y), "\n")

# torch.mm does NOT work with 1D or 3D tensors
print("\ntorch.mm only works with 2D tensors")
try:
    vec = torch.tensor([1, 2, 3])
    torch.mm(vec, vec)
except RuntimeError as e:
    print("vec: \n", vec, "\n")
    print(f"shape of vec: {vec.shape}, dimensions: {vec.dim()}")
    print(f"vec is a {vec.dim()}D tensor")
    print(f"Error with 1D tensors: {e}")

x (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]]) 

shape of x: torch.Size([2, 3]), dimensions: 2
x is a 2D tensor

y (3x2):
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) 

shape of y: torch.Size([3, 2]), dimensions: 2
y is a 2D tensor

torch.mm(x, y) (2x2):
 tensor([[ 58,  64],
        [139, 154]]) 


torch.mm only works with 2D tensors
vec: 
 tensor([1, 2, 3]) 

shape of vec: torch.Size([3]), dimensions: 1
vec is a 1D tensor
Error with 1D tensors: self must be a matrix


### torch.matmul

In [6]:
# torch.matmul - General matrix multiplication (supports broadcasting)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2x3
y = torch.tensor([[7, 8], [9, 10], [11, 12]])  # 3x2
print("torch.matmul(x, y):\n", torch.matmul(x, y))

print("\nWorks with 1D vectors (dot product):")
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
print("v1:", v1)
print(f"shape of v1: {v1.shape}, dimensions: {v1.dim()}")
print("v2:", v2)
print(f"shape of v2: {v2.shape}, dimensions: {v2.dim()}")
print("torch.matmul(v1, v2):", torch.matmul(v1, v2), "\n")

# works with higher dimensions and broadcasts:
# batch of matrices multiplied by single matrix
batch = torch.randn(3, 2, 4)  # 3 matrices of size 2x4 
mat = torch.randn(4, 5)  # single matrix of size 4x5

# The single matrix (4x5) is broadcast and multiplied with each of the 3 matrices (2x4), giving 3 result matrices (2x5)
result = torch.matmul(batch, mat)  # broadcasts to 3x2x5

print("Batch: \n", batch)
print(f"batch shape: {batch.shape}, dimensions: {batch.dim()}", "\n")
print("mat: \n", mat)
print(f"mat shape: {mat.shape}, dimensions: {mat.dim()}")
print(f"\n torch.matmul(batch, mat) shape: {result.shape}")

torch.matmul(x, y):
 tensor([[ 58,  64],
        [139, 154]])

Works with 1D vectors (dot product):
v1: tensor([1, 2, 3])
shape of v1: torch.Size([3]), dimensions: 1
v2: tensor([4, 5, 6])
shape of v2: torch.Size([3]), dimensions: 1
torch.matmul(v1, v2): tensor(32) 

Batch: 
 tensor([[[ 0.8543,  1.4464, -0.6485,  1.5200],
         [ 1.2156,  1.4097,  0.8729,  0.8012]],

        [[ 1.1347,  0.0215, -1.4591,  0.0403],
         [ 0.5238,  0.9281,  0.3071,  0.7228]],

        [[ 0.3621,  0.7618,  1.2185, -0.4246],
         [ 1.7410, -0.6459, -0.9263, -0.0328]]])
batch shape: torch.Size([3, 2, 4]), dimensions: 3 

mat: 
 tensor([[-0.0286, -0.4385, -0.8938,  0.1958,  1.1579],
        [ 2.4813,  0.6551,  0.3976, -0.9390,  0.0812],
        [ 1.2785,  0.5465,  0.8102, -0.6476, -0.0157],
        [ 0.5471,  1.6305, -0.0564,  0.6290, -0.9951]])
mat shape: torch.Size([4, 5]), dimensions: 2

 torch.matmul(batch, mat) shape: torch.Size([3, 2, 5])


### torch.bmm

In [41]:
# torch.bmm requires EXACTLY 3D tensors with same batch size
batch1 = torch.randn(10, 3, 4) # 10 matrices of size 3x4
batch2 = torch.randn(10, 4, 5) # 10 matrices of size 4x5
result = torch.bmm(batch1, batch2)  # results in 10x3x5
print(f"batch1 shape: {batch1.shape}")
print(f"batch2 shape: {batch2.shape}")
print(f"torch.bmm(batch1, batch2) shape: {result.shape}")

# Example where matmul works but bmm doesn't (broadcasting)
batch_a = torch.randn(5, 2, 3)  # 5 matrices of 2x3
batch_b = torch.randn(3, 4)     # single matrix of 3x4

print(f"\nbatch_a shape: {batch_a.shape}, batch_b shape: {batch_b.shape}")
print("torch.matmul can broadcast:", torch.matmul(batch_a, batch_b).shape)
try:
    torch.bmm(batch_a, batch_b)
except RuntimeError as e:
    print(f"torch.bmm cannot broadcast: {e}")

batch1 shape: torch.Size([10, 3, 4])
batch2 shape: torch.Size([10, 4, 5])
torch.bmm(batch1, batch2) shape: torch.Size([10, 3, 5])

batch_a shape: torch.Size([5, 2, 3]), batch_b shape: torch.Size([3, 4])
torch.matmul can broadcast: torch.Size([5, 2, 4])
torch.bmm cannot broadcast: batch2 must be a 3D tensor


## Broadcasting

In [42]:
# Broadcasting - Operating on tensors with different shapes
# Broadcasting allows PyTorch to automatically expand tensors to compatible shapes

# Scalar broadcasting
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
scalar = 10
print("a (2x3):\n", a)
print("scalar:", scalar)
print("\na + scalar (scalar is broadcast to match a's shape):\n", a + scalar) #scalar 10 becomes [[10, 10, 10], [10, 10, 10]]


a (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
scalar: 10

a + scalar (scalar is broadcast to match a's shape):
 tensor([[11, 12, 13],
        [14, 15, 16]])


In [43]:
# 1D to 2D broadcasting
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2x3
vector = torch.tensor([10, 20, 30])  # 3
print("matrix (2x3):\n", matrix)
print("vector (3,):", vector)
print("\nmatrix + vector:\n", matrix + vector)

#  vector [10, 20, 30] is broadcast to:
# [[10, 20, 30],
#  [10, 20, 30]]

matrix (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
vector (3,): tensor([10, 20, 30])

matrix + vector:
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [44]:
# Column vector broadcasting
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 2x3
col_vector = torch.tensor([[10], [20]])  # 2x1
print("matrix (2x3):\n", matrix)
print("col_vector (2x1):\n", col_vector)
print("\nmatrix + col_vector:\n", matrix + col_vector)

# col_vector [[10], [20]] is broadcast to:
# [[10, 20, 30],
#  [10, 20, 30]]

matrix (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
col_vector (2x1):
 tensor([[10],
        [20]])

matrix + col_vector:
 tensor([[11, 12, 13],
        [24, 25, 26]])


In [45]:
# "Two tensors are broadcastable if:"
# "1. Each tensor has at least one dimension, AND"
# "2. When iterating over dimensions from right to left:
#     - Dimensions are equal, OR"
#     - One of them is 1, OR"
#     - One of them doesn't exist"

# Example of compatible shapes
a = torch.randn(3, 1, 4)
b = torch.randn(1, 5, 4)
c = a + b
print(f"\na shape: {a.shape} (3, 1, 4)")
print(f"b shape: {b.shape} (1, 5, 4)")
print(f"Result shape: {c.shape}")

#   a: (3, 1, 4)
#   b: (1, 5, 4)
#       ↑  ↑  ↑
#     dim0 dim1 dim2

# Dim 2 (rightmost): a[4] vs b[4] → 4 == 4 ✓ Result: 4
# Dim 1 (middle): a[1] vs b[5] → 1 can broadcast to 5 ✓ Result: 5
#     - When one dimension is 1, it stretches/repeats to match the other
# Dim 0 (leftmost): a[3] vs b[1] → 1 can broadcast to 3 ✓ Result: 3
#     - Again, 1 broadcasts to match 3

# Final result: (3, 5, 4)

# What actually happens:
# - Tensor a (3, 1, 4): The middle dimension [1] is repeated 5 times
# - Tensor b (1, 5, 4): The first dimension [1] is repeated 3 times

# So effectively:
# - a becomes (3, 5, 4) by copying its single column 5 times
# - b becomes (3, 5, 4) by copying its single matrix 3 times


a shape: torch.Size([3, 1, 4]) (3, 1, 4)
b shape: torch.Size([1, 5, 4]) (1, 5, 4)
Result shape: torch.Size([3, 5, 4])


In [48]:
# Example 5: Incompatible shapes
x = torch.randn(3, 4)
y = torch.randn(3, 5)
print(f"x shape: {x.shape} (3, 4)")
print(f"y shape: {y.shape} (3, 5)")
print("\nDimension by dimension:")
print("  Dim 1: 4 != 5 and neither is 1 ✗")
try:
    z = x + y
except RuntimeError as e:
    print(f"\nError: {e}")


#   x: (3, 4)
#   y: (3, 5)
#       ↑  ↑
#      dim0 dim1

# 1. Dim 1 (rightmost): x[4] vs y[5] → 4 ≠ 5 and neither is 1 ✗ FAIL

# Broadcasting stops here!

# Why it fails:
# - For broadcasting to work, dimensions must be:
# - Equal (e.g., 4 == 4), OR
# - One of them is 1 (e.g., 1 can broadcast to any size), OR
# - One doesn't exist (e.g., (3,) can broadcast with (3, 4))

# Since 4 ≠ 5 and neither dimension is 1, PyTorch cannot automatically expand either tensor to make them compatible.

# If we wanted them to work:
# - Change y to (3, 4) → dimensions match
# - Change y to (3, 1) → the 1 can broadcast to 4
# - Change x to (3, 1) → the 1 can broadcast to 5

# But with 4 and 5, there's no way to broadcast - PyTorch won't guess which one you want!

x shape: torch.Size([3, 4]) (3, 4)
y shape: torch.Size([3, 5]) (3, 5)

Dimension by dimension:
  Dim 1: 4 != 5 and neither is 1 ✗

Error: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1


---

## Summary: Quick Reference

### Tensor Creation
| Function | Description |
|----------|-------------|
| `torch.tensor(data)` | Create from Python list/tuple |
| `torch.from_numpy(arr)` | Convert NumPy array (shares memory) |
| `torch.zeros(shape)` | All zeros |
| `torch.ones(shape)` | All ones |
| `torch.rand(shape)` | Random [0, 1) |
| `torch.randn(shape)` | Random normal (mean=0, std=1) |
| `torch.arange(start, end, step)` | Evenly spaced values |
| `torch.eye(n)` | Identity matrix |

### Shape Operations
| Operation | Description |
|-----------|-------------|
| `.view(shape)` | Reshape (must be contiguous) |
| `.reshape(shape)` | Reshape (works on any tensor) |
| `.squeeze()` | Remove dims of size 1 |
| `.unsqueeze(dim)` | Add dim of size 1 |
| `.flatten()` | Collapse to 1D |
| `.permute(dims)` | Reorder dimensions |
| `.T` | Transpose (2D only) |

### Key Operations
| Operation | Description |
|-----------|-------------|
| `+`, `-`, `*`, `/` | Element-wise arithmetic |
| `@`, `torch.matmul()` | Matrix multiplication |
| `.sum(dim)` | Sum along dimension |
| `.mean(dim)` | Mean along dimension |
| `.max(dim)` | Max along dimension |

### Device & Type
| Operation | Description |
|-----------|-------------|
| `.to('cuda')` | Move to GPU |
| `.to('cpu')` | Move to CPU |
| `.float()` | Convert to float32 |
| `.long()` | Convert to int64 |
| `.clone()` | Create independent copy |